INSERT INTO ds_parse_engine_binding(file_extension, engine_code, engine_name, is_default, enabled, sort_order) VALUES
    ('md', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 40),
    ('markdown', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 41),
    ('txt', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 42),
    ('text', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 43),
    ('sql', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 44),
    ('log', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 45),
    ('json', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 46),
    ('yaml', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 47),
    ('yml', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 48),
    ('xml', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 49),
    ('csv', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 50),
    ('properties', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 51),
    ('ini', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 52),
    ('conf', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 53),
    ('env', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 54),
    ('java', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 55),
    ('js', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 56),
    ('jsx', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 57),
    ('ts', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 58),
    ('tsx', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 59),
    ('py', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 60),
    ('go', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 61),
    ('sh', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 62),
    ('css', 'plain_text_java_engine', '通用文本直读引擎', 1, 1, 63),
    ('html', 'html_to_markdown_java_engine', 'HTML_to_Markdown_引擎', 1, 1, 70),
    ('htm', 'html_to_markdown_java_engine', 'HTML_to_Markdown_引擎', 1, 1, 71)
ON CONFLICT (file_extension, engine_code) DO UPDATE SET
    engine_name = EXCLUDED.engine_name,
    is_default = EXCLUDED.is_default,
    enabled = EXCLUDED.enabled,
    sort_order = EXCLUDED.sort_order,
    updated_at = CURRENT_TIMESTAMP;
